# Generated by Django 2.2 on 2019-04-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_auto_20190429_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
